#!/usr/bin/env node
/**
 * Stub Generator for Claw Build Errors
 *
 * Generates stub files for missing modules to quickly unblock the build.
 * These stubs should be replaced with proper implementations or removed later.
 *
 * Usage:
 *   node scripts/generate-stubs.mjs           # Generate stubs
 *   node scripts/generate-stubs.mjs --clean   # Remove generated stubs
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT_DIR = path.resolve(__dirname, '..');

const args = process.argv.slice(2);
const CLEAN = args.includes('--clean');

// Stub definitions - maps missing module path to stub content
const STUBS = {
  // PI Embedded Helpers - Core utilities that were removed
  'src/agents/pi-embedded-helpers.ts': {
    description: 'Core utility functions for PI embedded runner',
    exports: [
      { name: 'EmbeddedContextFile', type: 'type', definition: 'unknown' },
      { name: 'FailoverReason', type: 'type', definition: 'string' },
      { name: 'sanitizeUserFacingText', type: 'function', definition: '(text: string) => text' },
      { name: 'isMessagingToolDuplicate', type: 'function', definition: '() => false' },
      { name: 'isLikelyContextOverflowError', type: 'function', definition: '() => false' },
      { name: 'isCompactionFailureError', type: 'function', definition: '() => false' },
      { name: 'pickFallbackThinkingLevel', type: 'function', definition: '() => "medium"' },
      { name: 'formatBillingErrorMessage', type: 'function', definition: '() => ""' },
      { name: 'isRateLimitErrorMessage', type: 'function', definition: '() => false' },
    ]
  },

  // Channels allow-from
  'src/channels/allow-from.ts': {
    description: 'DM allow-from source merging utilities',
    exports: [
      { name: 'mergeDmAllowFromSources', type: 'function', definition: '() => ({})' },
      { name: 'resolveGroupAllowFromSources', type: 'function', definition: '() => ({})' },
    ]
  },

  // Channels normalize plugins
  'src/channels/plugins/normalize/whatsapp.ts': {
    description: 'WhatsApp normalization utilities (stub)',
    exports: [
      { name: 'normalizeWhatsAppAllowFromEntries', type: 'function', definition: '() => []' },
    ]
  },

  // CLI files
  'src/cli/outbound-send-deps.ts': {
    description: 'CLI outbound send dependencies (stub)',
    exports: [
      { name: 'OutboundSendDeps', type: 'type', definition: 'Record<string, unknown>' },
    ]
  },

  'src/cli/memory-cli.ts': {
    description: 'Memory CLI commands (stub)',
    exports: [
      { name: 'registerMemoryCli', type: 'function', definition: '() => {}' },
    ]
  },

  // Slack extension stubs (for code still referencing them)
  'src/channels/plugins/normalize/slack.ts': {
    description: 'Slack normalization utilities (stub)',
    exports: [
      { name: 'normalizeSlackAllowFromEntries', type: 'function', definition: '() => []' },
    ]
  },

  // Discord extension stubs
  'src/channels/plugins/normalize/discord.ts': {
    description: 'Discord normalization utilities (stub)',
    exports: [
      { name: 'normalizeDiscordAllowFromEntries', type: 'function', definition: '() => []' },
    ]
  },
};

// Track generated stubs
const generatedStubs = [];

/**
 * Generate TypeScript stub content
 */
function generateStubContent(stubDef) {
  const lines = [
    '/**',
    ` * ${stubDef.description}`,
    ' *',
    ' * @file STUB FILE - Generated by scripts/generate-stubs.mjs',
    ' * @warning This is a temporary stub. Replace with proper implementation or remove.',
    ' */',
    '',
  ];

  for (const exp of stubDef.exports) {
    if (exp.type === 'type') {
      lines.push(`export type ${exp.name} = ${exp.definition};`);
    } else if (exp.type === 'function') {
      lines.push(`export function ${exp.name}() { return ${exp.definition}; }`);
    } else if (exp.type === 'const') {
      lines.push(`export const ${exp.name} = ${exp.definition};`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Generate all stub files
 */
function generateStubs() {
  console.log('Generating stub files...\n');

  for (const [stubPath, stubDef] of Object.entries(STUBS)) {
    const fullPath = path.join(ROOT_DIR, stubPath);
    const dir = path.dirname(fullPath);

    // Create directory if it doesn't exist
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
      console.log(`Created directory: ${path.relative(ROOT_DIR, dir)}`);
    }

    // Generate stub content
    const content = generateStubContent(stubDef);

    // Write file
    fs.writeFileSync(fullPath, content);
    generatedStubs.push(fullPath);

    console.log(`Generated: ${stubPath}`);
    console.log(`  Exports: ${stubDef.exports.map(e => e.name).join(', ')}`);
  }

  // Write manifest of generated stubs
  const manifestPath = path.join(ROOT_DIR, 'stub-manifest.json');
  fs.writeFileSync(manifestPath, JSON.stringify({
    generated: new Date().toISOString(),
    stubs: Object.keys(STUBS),
    files: generatedStubs
  }, null, 2));

  console.log(`\nManifest written to: stub-manifest.json`);
  console.log(`\nTotal stubs generated: ${generatedStubs.length}`);
  console.log('\nNext steps:');
  console.log('  1. Run: pnpm build');
  console.log('  2. Fix any remaining type errors');
  console.log('  3. Track stubs for cleanup in CLEANUP_BACKLOG.md');
}

/**
 * Remove all generated stubs
 */
function cleanStubs() {
  console.log('Removing generated stub files...\n');

  const manifestPath = path.join(ROOT_DIR, 'stub-manifest.json');
  if (!fs.existsSync(manifestPath)) {
    console.log('No stub manifest found. Nothing to clean.');
    return;
  }

  const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));

  for (const stubFile of manifest.files) {
    if (fs.existsSync(stubFile)) {
      fs.unlinkSync(stubFile);
      console.log(`Removed: ${path.relative(ROOT_DIR, stubFile)}`);
    }
  }

  // Remove manifest
  fs.unlinkSync(manifestPath);
  console.log('\nStub manifest removed.');
  console.log(`Total stubs removed: ${manifest.files.length}`);
}

/**
 * Main entry point
 */
function main() {
  console.log('Stub Generator for Claw Build Errors');
  console.log('='.repeat(40) + '\n');

  if (CLEAN) {
    cleanStubs();
  } else {
    generateStubs();
  }
}

main();
